name: hoop
description: NBA app to keep up with all the live action from the NBA

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.2
  provider: ^4.3.2+2
  cached_network_image: ^2.3.3
  url_launcher: ^5.7.10
  splashscreen: ^1.3.3
  intl: ^0.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
    